/** Western campuses placed from operator pages and public location records. */
export interface DatacentreSite {
  id: string;
  title: string;
  lat: number;
  lng: number;
  place: string;
  url: string;
  detail: string;
}

export const DATACENTRES: DatacentreSite[] = [
  {
    id: "vantage-nv1",
    title: "Vantage NV1",
    lat: 39.55296,
    lng: -119.49077,
    place: "Sparks, Nevada",
    url: "https://vantage-dc.com/data-center-locations/north-america/reno-nevada/",
    detail: "1121 USA Parkway",
  },
  {
    id: "apple-reno",
    title: "Apple",
    lat: 39.56616,
    lng: -119.54797,
    place: "Sparks, Nevada",
    url: "https://dgtlinfra.com/apple-data-center-locations/",
    detail: "21505 Reno Technology Parkway",
  },
  {
    id: "switch-las-vegas",
    title: "Switch SUPERNAP",
    lat: 36.06,
    lng: -115.2102,
    place: "Las Vegas, Nevada",
    url: "https://www.switch.com/",
    detail: "7135 South Decatur Boulevard",
  },
  {
    id: "meta-los-lunas",
    title: "Meta",
    lat: 34.82803,
    lng: -106.78028,
    place: "Los Lunas, New Mexico",
    url: "https://www.datacenters.com/facebook-los-lunas",
    detail: "4250 Messenger Loop",
  },
  {
    id: "apple-mesa",
    title: "Apple",
    lat: 33.34725,
    lng: -111.60322,
    place: "Mesa, Arizona",
    url: "https://dgtlinfra.com/apple-data-center-locations/",
    detail: "3740 South Signal Butte Road",
  },
  {
    id: "meta-mesa",
    title: "Meta",
    lat: 33.34667,
    lng: -111.62967,
    place: "Mesa, Arizona",
    url: "https://www.datacenters.com/facebook-los-lunas",
    detail: "3841 South Ellsworth Road",
  },
  {
    id: "equinix-sv17",
    title: "Equinix SV17",
    lat: 37.37647,
    lng: -121.98858,
    place: "Santa Clara, California",
    url: "https://www.equinix.com/data-centers/americas-colocation/united-states-colocation/silicon-valley-data-centers",
    detail: "3030 Corvin Drive",
  },
  {
    id: "coresite-la1",
    title: "CoreSite LA1",
    lat: 34.04797,
    lng: -118.25556,
    place: "Los Angeles, California",
    url: "https://www.coresite.com/data-centers/locations/los-angeles",
    detail: "624 South Grand Avenue",
  },
  {
    id: "digital-realty-paul",
    title: "Digital Realty",
    lat: 37.72384,
    lng: -122.39792,
    place: "San Francisco, California",
    url: "https://www.digitalrealty.com/data-centers/americas/san-francisco",
    detail: "200 Paul Avenue",
  },
  {
    id: "digital-realty-365",
    title: "Digital Realty",
    lat: 37.78863,
    lng: -122.39068,
    place: "San Francisco, California",
    url: "https://www.digitalrealty.com/data-centers/americas/san-francisco",
    detail: "365 Main Street",
  },
  {
    id: "coresite-denver",
    title: "CoreSite Denver",
    lat: 39.74562,
    lng: -104.99563,
    place: "Denver, Colorado",
    url: "https://www.coresite.com/data-centers/locations/denver",
    detail: "910 15th Street",
  },
  {
    id: "meta-eagle-mountain",
    title: "Meta",
    lat: 40.2688261,
    lng: -112.0175808,
    place: "Eagle Mountain, Utah",
    url: "https://www.openstreetmap.org/search?query=Meta%20Eagle%20Mountain%20Data%20Center",
    detail: "Eagle Mountain campus",
  },
  {
    id: "utah-data-center",
    title: "Utah Data Center",
    lat: 40.4281923,
    lng: -111.9343502,
    place: "Bluffdale, Utah",
    url: "https://en.wikipedia.org/wiki/Utah_Data_Center",
    detail: "Camp Williams",
  },
  {
    id: "google-the-dalles",
    title: "Google",
    lat: 45.6321521,
    lng: -121.2015614,
    place: "The Dalles, Oregon",
    url: "https://www.google.com/about/datacenters/locations/the-dalles/",
    detail: "The Dalles campus",
  },
  {
    id: "creekstone-delta",
    title: "Creekstone Delta",
    lat: 39.35241,
    lng: -112.57928,
    place: "Delta, Utah",
    url: "https://www.creekstone.energy/delta",
    detail: "Campus under construction",
  },
  {
    id: "project-jupiter",
    title: "Project Jupiter",
    lat: 31.85843,
    lng: -106.64709,
    place: "Santa Teresa, New Mexico",
    url: "https://www.abqjournal.com/business/doa-ana-countys-project-jupiter-joins-500-billion-stargate-initiative-led-by-openai-oracle/493927",
    detail: "Stargate campus in Doña Ana County",
  },
];
